#pragma once
#include <entt/entt.hpp>
#include <spdlog/spdlog.h>
#include "Mui.h"
#include "addons/bxImGui/src/MainMenuBar.h"
#include "core/AddonBase.h"
#include "core/IApp.h"
#include "core/MAddon.h"
#include "core/WindowSettings.h"
#include "core/canvas/MCanvas.h"
#include "core/util/MSettings.h"
#include "ecs/MEcs.h"
#include "rendering/MRendering.h"
