#pragma once
#include <entt/entt.hpp>
#include <spdlog/spdlog.h>
#include "core/IApp.h"
#include "core/IWindow.h"
#include "core/WindowSettings.h"
#include "core/addon/IAddon.h"
#include "core/addon/MAddon.h"
#include "core/canvas/MCanvas.h"
#include "core/util/MSettings.h"
#include "ecs/MEcs.h"
#include "rendering/MRendering.h"
