name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-14
      - name: Check formatting
        run: |
          git fetch origin main --depth=1
          BASE=$(git merge-base origin/main HEAD)
          FILES=$(git diff --name-only $BASE HEAD -- '*.cpp' '*.h' '*.c' '*.hpp' | grep -vE '^(third_party|assets|addons)/' | xargs)
          if [ -n "$FILES" ]; then
            echo "Checking clang-format on changed files:" $FILES
            clang-format-14 --dry-run --Werror $FILES
          else
            echo "No source files changed. Skipping clang-format check."
          fi 
