name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format-14
      - name: Check formatting
        run: |
          # Get the base commit for comparison
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE=${{ github.event.pull_request.base.sha }}
          else
            # For pushes, compare with the previous commit
            BASE=$(git rev-parse HEAD~1)
          fi
          
          FILES=$(git diff --name-only $BASE HEAD -- '*.cpp' '*.h' '*.c' '*.hpp' | grep -vE '^(third_party|assets|addons)/')
          if [ -n "$FILES" ]; then
            # Filter out deleted files and only check existing files
            EXISTING_FILES=""
            for file in $FILES; do
              if [ -f "$file" ]; then
                EXISTING_FILES="$EXISTING_FILES $file"
              fi
            done
            if [ -n "$EXISTING_FILES" ]; then
              echo "Checking clang-format on changed files:$EXISTING_FILES"
              clang-format-14 --dry-run --Werror $EXISTING_FILES
            else
              echo "No existing source files to check. Skipping clang-format check."
            fi
          else
            echo "No source files changed. Skipping clang-format check."
          fi 
